<a href="https://colab.research.google.com/github/dorahs71/ml-course/blob/main/mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

講義如果寫(tensorflow 1.x)

from keras...
全部改成(tensorflow 2.x)

from tensorflow.keras

In [41]:
from tensorflow.keras.datasets import mnist
# ((訓練圖片, 答案), (測試圖片, 答案))
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [42]:
x_train[0] # 共有 28 個像素，代表以下顯示的「5」圖片

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 170,
        253, 253, 253, 253, 253, 225, 172, 253, 242, 195,  64,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  49, 238, 253, 253, 253, 253,
        253, 253, 253, 253, 251,  93,  82,  82,  56,  39,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  18, 219, 253, 253, 253, 253,
        253, 198, 182, 247, 241,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  80, 156, 107, 253, 253,
        205,  11,   0,  43, 154,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14,   1, 154, 253,
         90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 139, 253,
        190,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11, 190,
        253,  70,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  35,
        241, 225, 160, 108,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         81, 240, 253, 253, 119,  25,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  45, 186, 253, 253, 150,  27,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  16,  93, 252, 253, 187,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 249, 253, 249,  64,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  46, 130, 183, 253, 253, 207,   2,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  39,
        148, 229, 253, 253, 253, 250, 182,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  24, 114, 221,
        253, 253, 253, 253, 201,  78,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  23,  66, 213, 253, 253,
        253, 253, 198,  81,   2,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  18, 171, 219, 253, 253, 253, 253,
        195,  80,   9,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,  55, 172, 226, 253, 253, 253, 253, 244, 133,
         11,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 136, 253, 25

In [43]:
#灰階圖片 0 代表黑色, 255 代表白色
import pandas as pd

pd.DataFrame(x_train[0])

0   1   2   3    4    5    6    7    8    9   ...   18   19   20   21   22   23  24  25  26  27
0    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
1    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
2    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
3    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
4    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
5    0   0   0   0    0    0    0    0    0    0  ...  175   26  166  255  247  127   0   0   0   0
6    0   0   0   0    0    0    0    0   30   36  ...  225  172  253  242  195   64   0   0   0   0
7    0   0   0   0    0    0    0   49  238  253  ...   93   82   82   56   39    0   0   0   0   0
8    0   0   0   0    0    0    0   18  219  253  ...    0    0    0    0    0    0   0   0   0   0
9    0   0   0   0    0    0    0    0   80  156  ...    0    0    0    0    0    0   0   0   0   0
10   0   0   0   0    0    0    0    0    0   14  ...    0    0    0    0    0    0   0   0   0   0
11   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
12   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
13   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
14   0   0   0   0    0    0    0    0    0    0  ...   25    0    0    0    0    0   0   0   0   0
15   0   0   0   0    0    0    0    0    0    0  ...  150   27    0    0    0    0   0   0   0   0
16   0   0   0   0    0    0    0    0    0    0  ...  253  187    0    0    0    0   0   0   0   0
17   0   0   0   0    0    0    0    0    0    0  ...  253  249   64    0    0    0   0   0   0   0
18   0   0   0   0    0    0    0    0    0    0  ...  253  207    2    0    0    0   0   0   0   0
19   0   0   0   0    0    0    0    0    0    0  ...  250  182    0    0    0    0   0   0   0   0
20   0   0   0   0    0    0    0    0    0    0  ...   78    0    0    0    0    0   0   0   0   0
21   0   0   0   0    0    0    0    0   23   66  ...    0    0    0    0    0    0   0   0   0   0
22   0   0   0   0    0    0   18  171  219  253  ...    0    0    0    0    0    0   0   0   0   0
23   0   0   0   0   55  172  226  253  253  253  ...    0    0    0    0    0    0   0   0   0   0
24   0   0   0   0  136  253  253  253  212  135  ...    0    0    0    0    0    0   0   0   0   0
25   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
26   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0
27   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0    0    0   0   0   0   0

[28 rows x 28 columns]

In [44]:
# model 有兩種方式 Sequential(堆疊) Model(複雜)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense #全連接層(fully-connected)
# https://keras.io/api/layers/core_layers/dense/

layers = [
    # 784 * 64 + 64(bias)
    Dense(64, activation="sigmoid", input_dim=784), #784 變 64 再變 10
    # 標準化(加起來=1) 的就叫做 softmax
    # 係數 64 * 10 + 10(bias)
    Dense(10, activation="sigmoid")
    # 之所以是 10 層是因為，圖片中顯示的是 0 ~ 9 的阿拉伯數字，所以總共有 10 個可能性，若圖片是 5 ，則
    # 5 的判斷值為 1，其餘為 0 => [0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ]，加總起來一行就簡化為 1
    # 超參數 - 隨便選的參數，反正結果好就好了，如果發現結果很爛就再換
]

model = Sequential(layers)

model.summary()


Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 64)                50240     
                                                                 
 dense_9 (Dense)             (None, 10)                650       
                                                                 
Total params: 50890 (198.79 KB)
Trainable params: 50890 (198.79 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [45]:
model.compile(loss="mse", metrics=["accuracy"])

In [46]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


In [47]:
from tensorflow.keras.utils import to_categorical

y_train_onehot = to_categorical(y_train)
y_test_onehot = to_categorical(y_test)

print(y_train[0])
print(y_train_onehot[0])

5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [48]:
# 其實係數不是完全隨機，他是在某個範圍做隨機，其實變相要求你的輸入應該要落在某個範圍
# tensorflow 希望你的輸入落在 0~1 或者 -1~1

x_train_scaled = x_train.reshape(60000, 784) / 255.0 #也可以寫成 x_train.reshape(-1, 784)
x_test_scaled = x_test.reshape(10000, 784) / 255.0

在這段代碼中，`/ 255.0` 的操作是對像素值進行標準化。這是因為圖像數據通常以 0 到 255 之間的整數表示每個像素的灰度值或 RGB 值。對數據進行標準化的原因包括以下幾點：

1. **統一數據範圍**：
   - 將像素值範圍從 0-255 轉換到 0-1，可以統一數據範圍，使得所有像素值在相同的尺度上，這有助於提高模型的訓練效果。

2. **加快收斂速度**：
   - 在訓練神經網絡時，標準化數據可以加快梯度下降算法的收斂速度，從而加快訓練過程。

3. **穩定數值計算**：
   - 將數據縮放到 0-1 範圍內，可以避免大數值計算引起的數值不穩定性，從而提高計算的穩定性和模型的性能。

具體來說，這段代碼的每一步解釋如下：

```python
x_train_scaled = x_train.reshape(60000, 784) / 255.0  # 也可以寫成 x_train.reshape(-1, 784)
x_test_scaled = x_test.reshape(10000, 784) / 255.0
```

1. **`reshape` 操作**：
   - `x_train.reshape(60000, 784)` 將原始形狀為 `(60000, 28, 28)` 的 `x_train` 數據集重新整形為 `(60000, 784)`，即將每張 28x28 的圖像展平為一個 784 維的向量。
   - `x_train.reshape(-1, 784)` 是一個簡便寫法，其中 `-1` 會自動計算出所需的行數，這裡會得到相同的結果。

2. **`/ 255.0` 操作**：
   - 將每個像素值除以 255，將像素值從原始的 0-255 範圍縮放到 0-1 範圍。這樣做的目的是進行數據標準化。

這樣的標準化對於訓練神經網絡或其他機器學習模型是很有幫助的，因為它可以讓模型更快更穩定地收斂，提高預測精度。

In [51]:
# batch_size: 看了多少筆才更新一次模型參數 (100 是老師自己選的)
# epochs: 整份資料(60000筆)要看幾 round
# 究竟是幾 round 咧？ 我們不會無限訓練下去(當然loss 會越來越小) -> 過擬和
# -> 只看 validation_loss 來決定到底要訓練幾個 epochs，不看 val_accuracy，因為可能賽對
# 跟機器學習一樣，要準備一份電腦沒看過的，來檢視現在的擬和程度
# batch=100, vali=0.1, 1 個epoch 做了幾次模型更新：54000/100 = 540 => 總共做了 540 次模型更新
# verbose: 印 log 的程度, 0(quiet), 1(bar), 2(沒有bar)

model.fit(x_train_scaled,
          y_train_onehot,
          batch_size=100,
          epochs=30,
          validation_split=0.1,
          verbose=2)

Epoch 1/30
540/540 - 2s - loss: 0.0068 - accuracy: 0.9632 - val_loss: 0.0059 - val_accuracy: 0.9688 - 2s/epoch - 4ms/step
Epoch 2/30
540/540 - 1s - loss: 0.0067 - accuracy: 0.9640 - val_loss: 0.0058 - val_accuracy: 0.9687 - 1s/epoch - 3ms/step
Epoch 3/30
540/540 - 2s - loss: 0.0066 - accuracy: 0.9643 - val_loss: 0.0058 - val_accuracy: 0.9693 - 2s/epoch - 3ms/step
Epoch 4/30
540/540 - 2s - loss: 0.0065 - accuracy: 0.9648 - val_loss: 0.0058 - val_accuracy: 0.9707 - 2s/epoch - 3ms/step
Epoch 5/30
540/540 - 3s - loss: 0.0064 - accuracy: 0.9655 - val_loss: 0.0057 - val_accuracy: 0.9703 - 3s/epoch - 5ms/step
Epoch 6/30
540/540 - 2s - loss: 0.0063 - accuracy: 0.9660 - val_loss: 0.0056 - val_accuracy: 0.9713 - 2s/epoch - 3ms/step
Epoch 7/30
540/540 - 2s - loss: 0.0062 - accuracy: 0.9664 - val_loss: 0.0056 - val_accuracy: 0.9717 - 2s/epoch - 3ms/step
Epoch 8/30
540/540 - 2s - loss: 0.0062 - accuracy: 0.9671 - val_loss: 0.0055 - val_accuracy: 0.9700 - 2s/epoch - 3ms/step
Epoch 9/30
540/540 - 2s 